name: Build and Deploy pkgdown site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # 3️⃣ Cache R packages
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      # 4️⃣ Install package dependencies
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "pkgdown", "devtools"))
          remotes::install_deps(dependencies = TRUE)

      # 5️⃣ Install your package
      - name: Install IntegratedLearner
        run: |
          R CMD INSTALL .

      # 6️⃣ Build pkgdown site
      - name: Build site
        run: |
          R -e "pkgdown::build_site()"

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
